---
title: "Exercises"
---

# Part I:

1)  Create a vector of even numbers, from 2 to 100. and store it in an object.

2)  Create another vector ranging from 1 to 50 and store it in an object

3)  Run the below lines of code. Put the 'binary' vector along with the two vectors you just made in a data frame and store it in an object. set.seed(42) binary \<- rbinom(50, 1, 0.5)

4)  Filter the data frame you just made for rows where the binary variable is equal to 1. Store the output in a new object

5)  Pull the first vector you made in question 1 out of the object from question 4. Try doing this with both the `$` operator and doubled-up square brackets `[[]]`.

# Part II:

1)  read in the simpsons_episodes.csv file from the 'data' folder and store it in an object. Take a moment to explore it (hint - names() and str() will be useful here).

2)  make a vector denoting whether the IMBD rating for an episode is above 8. Try to do this using both base R and the tidyverse.

3)  Filter for the first ten season and select, IMDB ratings, episode id, season number, title, and view number. Try to do it with both base R and the tidyverse. Store the output in a new object.

4)  In this object, create a new variable showing the rating per views. Try doing this with both base R and the tidyverse.

5)  Check out the write.csv function. Save the data frame you've ended up with after question 4 in the 'data' folder UNDER A DIFFERENT NAME! (Tips: ? write.csv)

# Part III:
1) Get a summary of the 'redistribution' variable from the CHES dataset. Put the same variable through Psych's describe() function


2) Describe the redistribution variable by party for the German (country = 3) data in CHES. Feel free to use any mix of base R or tidyverse you want.


3) Read in the simpsons_episodes.csv file from the 'data' folder. Make a boxplot of the IMDB ratings variable in base R.


4) Make a scatter plot of IMDB ratings and season. Store the plot in an object.


5) Add a theme and a regression line to the object you just made - so if your object is called myPlot, myPlot + theme() will for instance work. I.e. you can keep adding to ggplots after you've stored them in an object! (note that this won't overwrite the object unless you assign it)


# Part IV:
1) Run a t-test on the mean user rating in the books data frame.


2) Run another t-test, this time testing the difference in mean price between fiction and non-fiction books. Feel free to use either Base R or the tidyverse.


3) Read in the simpsons_episodes.csv file from the data folder and store
it in an object. Build and run an OLS model regressing IMDB rating on season.
 tore the result in an object.


4) Run another model regressing IMDB rating on both season and views. Store this in another object.


5) Print out the results from questions 3 and 4 next to each other using screenreg(). If you're feeling brave, check out the help file and try to customise the output.
